Remove Premake

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -139,13 +139,7 @@ jobs:
 
   - bash: |
       set -e
-      pushd $AGENT_TEMPDIRECTORY
-      export PREMAKE_MAC=https://github.com/premake/premake-core/releases/download/v5.0.0-alpha14/premake-5.0.0-alpha14-macosx.tar.gz
-      curl -L $PREMAKE_MAC --output premake5.tar.gz
-      tar zxvf premake5.tar.gz
-      popd
 
-      export PATH=$AGENT_TEMPDIRECTORY:$PATH
       ./build-osx.sh --build --verbose
 
       # In the release pipeline we also want the surge-fx
@@ -179,19 +173,23 @@ jobs:
 
   - bash: |
       set -e
-      pushd $AGENT_TEMPDIRECTORY
-      export PREMAKE_WINDOWS=https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-windows.zip
-      curl -L $PREMAKE_WINDOWS --output premake5.zip
-      unzip premake5.zip
-      popd
 
-      export PATH=$AGENT_TEMPDIRECTORY:$PATH
-      premake5 vs2017
-      ls -alFh
+      mkdir -p build
+      cmake -Bbuild -A x64
 
       # need this because MSBuild.restoreNugetPackages: true fails
       nuget restore .
-    condition: variables.isWindows
+    condition: and(variables.isWindows, variables.x64)
+    displayName: Setup Windows Project
+
+  - bash: |
+      set -e
+
+      mkdir -p build
+      cmake -Bbuild -A Win32
+      # need this because MSBuild.restoreNugetPackages: true fails
+      nuget restore .
+    condition: and(variables.isWindows, variables.x86)
     displayName: Setup Windows Project
 
   - task: MSBuild@1
@@ -297,12 +295,7 @@ jobs:
 
   - bash: |
       set -x
-      pushd $AGENT_TEMPDIRECTORY
-      export PREMAKE_LINUX=https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz
-      curl -L $PREMAKE_LINUX --output premake5.tar.gz
-      tar zxvf premake5.tar.gz
-      export PATH=$AGENT_TEMPDIRECTORY:$PATH
-      popd
+
       sudo apt-get install -y libgtkmm-3.0-dev
       sudo apt-get install -y xcb
       sudo apt-get install -y libxcb-util-dev
